; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter, extra scripting
;   Upload options: custom port, speed and extra flags
;   Library options: dependencies, extra library storages
;
; Please visit documentation for the other options and examples
; http://docs.platformio.org/en/stable/projectconf.html

[platformio]
#default_envs = openevse
src_dir = firmware/open_evse

extra_configs =
	firmware/variants/*/platformio.ini

[common]
lib_deps =
version = D8.2.3
build_src_filter =
   +<*.cpp>
build_flags =
  -D OEV6
  -D RELAY_PWM
  -D SHOW_DISABLED_TESTS
  -D AMMETER
  -D RAPI
  -D RAPI_SERIAL
  -D RAPI_WF
  -D RAPI_BTN
  #-D TIME_LIMIT
  #-D CHARGE_LIMIT
  -D MENNEKES_LOCK
  -D HEARTBEAT_SUPERVISION
us_build_flags =
  ${common.build_flags}
  -D AUTOSVCLEVEL
  #-D BOOTLOCK
eu_build_flags =
  ${common.build_flags}
  -D NO_AUTOSVCLEVEL
  -D PERIODIC_LCD_REFRESH_MS=120000UL
  -D DEFAULT_CURRENT_CAPACITY_L2=32
  -D MAX_CURRENT_CAPACITY_L2=32
  -D OVERCURRENT_THRESHOLD=5
  -D OVERCURRENT_TIMEOUT=10000UL
  -D DEFAULT_SERVICE_LEVEL=2


[env:samd21g18a]
platform = atmelsam
framework = arduino
board = samd21g18a

