; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter, extra scripting
;   Upload options: custom port, speed and extra flags
;   Library options: dependencies, extra library storages
;
; Please visit documentation for the other options and examples
; http://docs.platformio.org/en/stable/projectconf.html

[platformio]
#default_envs = openevse
src_dir = firmware/open_evse

extra_configs =
	firmware/targets/*/platformio.ini

[common]
lib_deps =
version = D9.0.0
build_src_filter =
   +<*.cpp>
build_flags =
  -D WATCHDOG # watchdog MUST be enabled; only turn it off during debugging
  -D WATCHDOG_TIMEOUT_SEC=2 # do not change this value
  -D AMMETER
  -D RAPI
  -D RAPI_SERIAL
  -D RAPI_WF
  -D RAPI_BTN
  -D MENNEKES_LOCK
  -D PP_AUTO_AMPACITY
  -D BOOTLOCK
  -D HEARTBEAT_SUPERVISION
  -D TEMPERATURE_THROTTLING
  -D DEFAULT_SERVICE_LEVEL=2
  -D DEFAULT_CURRENT_CAPACITY_L2=24
  -D MAX_CURRENT_CAPACITY_L2=80
  -D OVERCURRENT_THRESHOLD=5
  -D OVERCURRENT_TIMEOUT=10000UL
  -D PERIODIC_LCD_REFRESH_MS=120000UL
  -D NO_GROUND_RECORD_DELAY=2000
  -D RELAY_ZC_SWITCH