
[m328p]
upload_protocol = usbasp
upload_flags = "-e -B0.5"
lib_deps = ${common.lib_deps}
build_src_flags =
  -D TARGET_M328P
  -D RAPI_SERIAL_PORT=Serial
  -D OEV6
  -D RELAY_PWM
  -D SHOW_DISABLED_TESTS
  -I firmware/targets/m328p
  ${common.us_build_flags}
build_src_filter =
  ${common.build_src_filter}
  +<../targets/m328p>

# v6 CGMI OpenEVSE
[env:m328p_v6]
platform = atmelavr@3.4.0
board = openevse
framework = arduino
upload_protocol = ${m328p.upload_protocol}
upload_flags = ${m328p.upload_flags}
lib_deps = ${m328p.lib_deps}
build_src_filter =
  ${m328p.build_src_filter}
build_src_flags=
  ${m328p.build_src_flags}
  -D ENABLE_CGMI
  -D NO_GROUND_RECORD_DELAY=2000
  -D NO_AUTOSVCLEVEL
  -D DEFAULT_SERVICE_LEVEL=2
  -D OVERCURRENT_THRESHOLD=5
  -D OVERCURRENT_TIMEOUT=10000UL
  -D BOOTLOCK
  -D 'VERSION="${common.version}.CGMI"'

# EU OpenEVSE
[env:m328p_eu]
extends = env:m328p_v6
build_src_flags=
  ${m328p.build_src_flags}
  ${common.eu_build_flags}
  -D MV_FOR_L2=230000L
  -D 'VERSION="${common.version}.EU"'

# Non-tethered T2 EmonEVSE single-phase
[env:m328p_emonevse]
extends = env:m328p_v6
build_src_flags=
  ${m328p.build_src_flags}
  ${common.eu_build_flags}
  -D PP_AUTO_AMPACITY
  -D MV_FOR_L2=230000L
  -D 'VERSION="${common.version}.T2"'

# legacy openevse with 16x2 RGBLCD and front panel button
[env:m328p_rgblcd]
extends = env:m328p_v6
build_src_flags=
  ${m328p.build_src_flags}
  -UOEV6
  -UHEARTBEAT_SUPERVISION
  -UBOOTLOCK
  -D ENABLE_CGMI
  -D OVERCURRENT_THRESHOLD=5
  -D OVERCURRENT_TIMEOUT=10000UL
  -D BTN_MENU
  -D HAVE_RTC
  -D DELAY_TIMER
  -D RGBLCD
  -D CHARGE_LIMIT
  -D TIME_LIMIT
  -D TEMPERATURE_THROTTLING
  -D 'VERSION="${common.version}"'

# Non-tethered T2 EmonEVSE three-phase
# Deprecated, unneeded with wifi fw > 4.1.7
; [env:emonevse_3ph]
; extends = env:m328p
; build_src_flags=
;   ${common.eu_build_flags}
;   -D PP_AUTO_AMPACITY
;   -D THREEPHASE
;   -D 'VERSION="${common.version}.3P"'


