
[m328p]
upload_protocol = usbasp
upload_flags = "-e -B0.5"
lib_deps = ${common.lib_deps}
build_src_flags =
  ${common.build_flags}
  -D TARGET_M328P
  -D RAPI_SERIAL_PORT=Serial
  -D OEV6
  -D RELAY_PWM
  -D SHOW_DISABLED_TESTS
  -I firmware/targets/m328p
build_src_filter =
  ${common.build_src_filter}
  +<../targets/m328p>

# v5 OpenEVSE
[env:m328p_v5]
platform = atmelavr@3.4.0
board = openevse
framework = arduino
upload_protocol = ${m328p.upload_protocol}
upload_flags = ${m328p.upload_flags}
lib_deps = ${m328p.lib_deps}
build_src_filter =
  ${m328p.build_src_filter}
build_src_flags=
  ${m328p.build_src_flags}
 -D 'VERSION="${common.version}"'

 # v6 CGMI OpenEVSE
[env:m328p_v6]
extends = env:m328p_v5
build_src_flags=
  ${m328p.build_src_flags}
  -D ENABLE_CGMI
  -D 'VERSION="${common.version}.CGMI"'

 # v5 OpenEVSE RTC LCD BTN
[env:m328p_v5_RTC_BTN_LCD]
extends = env:m328p_v5
build_src_flags=
  ${m328p.build_src_flags}
  -D AUTOSVCLEVEL
  -D BTN_MENU
  -D HAVE_RTC
  -D DELAY_TIMER
  -D RGBLCD
  -D CHARGE_LIMIT
  -D TIME_LIMIT
  -D TEMPERATURE_THROTTLING
  -D 'VERSION="${common.version}.v5RTCRGBLCD"'

# openevse v6 with 16x2 RGBLCD and front panel button
[env:m328p_v6_RTC_BTN_LCD]
extends = env:m328p_v6
build_src_flags=
  ${m328p.build_src_flags}
  -D ENABLE_CGMI
  -D BTN_MENU
  -D HAVE_RTC
  -D DELAY_TIMER
  -D RGBLCD
  -D CHARGE_LIMIT
  -D TIME_LIMIT
  -D TEMPERATURE_THROTTLING
  -D 'VERSION="${common.version}.CGMI_RTCRGBLCD"'

   





