
[m328p]
upload_protocol = usbasp
upload_flags = "-e -B0.5"
lib_deps = ${common.lib_deps}
build_src_flags =
  ${common.build_flags}
  -D TARGET_M328P
  -D OEV6
  -D RAPI_SERIAL_PORT=Serial
  -D RELAY_PWM
  -D SHOW_DISABLED_TESTS
  -I firmware/targets/m328p
build_src_filter =
  ${common.build_src_filter}
  +<../targets/m328p>

 # WiFi with TFT
[env:m328p_TFT_WIFI]
platform = atmelavr@3.4.0
board = openevse
framework = arduino
upload_protocol = ${m328p.upload_protocol}
upload_flags = ${m328p.upload_flags}
lib_deps = ${m328p.lib_deps}
build_src_filter =
  ${m328p.build_src_filter}
build_src_flags=
  ${m328p.build_src_flags}
  -D AUTOSVCLEVEL
  -D 'VERSION="${common.version}.TFTWIFI"'

 # WiFi with LCD
[env:m328p_LCD_WIFI]
extends = env:m328p_TFT_WIFI
platform = atmelavr@3.4.0
board = openevse
framework = arduino
build_src_flags=
  ${m328p.build_src_flags}
  -D RGBLCD
  -D 'VERSION="${common.version}.LCDWIFI"'

 # legacy RTC LCD BTN no WiFi
[env:m328p_noWiFi_RTC_BTN_LCD]
extends = env:m328p_LCD_WIFI
platform = atmelavr@3.4.0
board = openevse
framework = arduino
build_src_flags=
  ${m328p.build_src_flags}
  -UHEARTBEAT_SUPERVISION
  -UBOOTLOCK
  -D BTN_MENU
  -D HAVE_RTC
  -D DELAY_TIMER
  -D RGBLCD
  -D CHARGE_LIMIT
  -D TIME_LIMIT
  -D 'VERSION="${common.version}.noWIFI"'
   





