[samd]
lib_deps = ${common.lib_deps}
  https://github.com/lincomatic/Adafruit_SleepyDog.git
;extra_scripts = pre:firmware/targets/samd/no_erase_upload.py
build_src_flags =
  -D TARGET_SAMD
  -D EEPROM_FLASH_STORE_KB=48
  -D RAPI_SERIAL_PORT=Serial1
  -D ENABLE_CGMI
  -D NO_GROUND_RECORD_DELAY=2000
  -D NO_AUTOSVCLEVEL
  -D DEFAULT_SERVICE_LEVEL=2
  -D OVERCURRENT_THRESHOLD=5
  -D OVERCURRENT_TIMEOUT=10000UL
  -D BOOTLOCK
  -I firmware/targets/samd
  ${common.us_build_flags}
build_src_filter =
  ${common.build_src_filter}
  +<../targets/samd>


# SAMD CGMI OpenEVSE
[env:samd_us]
platform = atmelsam
framework = arduino
board = zeroUSB
build_type = release
#board = samd21g18a
monitor_speed=115200
;extra_scripts = ${samd.extra_scripts}
lib_deps = ${samd.lib_deps}
build_src_filter =
  ${samd.build_src_filter}
build_src_flags=
  ${samd.build_src_flags}
  -D 'VERSION="${common.version}.SAMD"'

# # SAMD CGMI OpenEVSE (Atmel-ICE upload/programming)
[env:samd_us_ice]
extends = env:samd_us
upload_protocol = atmel-ice
build_type = release
build_src_flags=
  ${env:samd_us.build_src_flags}

[env:samd_us_ice_dev] ; don't use this.. for dev/debug only
extends = env:samd_us
upload_protocol = atmel-ice
build_type = release ;debug
;debug_tool = atmel-ice
build_src_flags=
  ${env:samd_us.build_src_flags}
  ;-UWATCHDOG
  -UBOOTLOCK
  -UHEARTBEAT_SUPERVISION
  -DBYPASS_GFI ; disable GFI
;  -DCALIBRATE ; pilot calibration mode - for initial setup only
;  -DAMMETER_TEST ; ammeter test mode - for initial setup only

# EU OpenEVSE
[env:samd_eu]
extends = env:samd_us
;extra_scripts = ${samd.extra_scripts}
build_src_flags=
  ${samd.build_src_flags}
  ${common.eu_build_flags}
  -D MV_FOR_L2=230000L
  -D 'VERSION="${common.version}.EU"'

# Non-tethered T2 EmonEVSE single-phase
[env:samd_emonevse]
extends = env:samd_us
;extra_scripts = ${samd.extra_scripts}
build_src_flags=
  ${samd.build_src_flags}
  ${common.eu_build_flags}
  -D PP_AUTO_AMPACITY
  -D MV_FOR_L2=230000L
  -D 'VERSION="${common.version}.T2"'

# Non-tethered T2 EmonEVSE three-phase
# Deprecated, unneeded with wifi fw > 4.1.7
; [env:emonevse_3ph]
; extends = env:openevse
; build_src_flags=
;   ${common.eu_build_flags}
;   -D PP_AUTO_AMPACITY
;   -D THREEPHASE
;   -D 'VERSION="${common.version}.3P"'


