
[m328p]
upload_protocol = usbasp
upload_flags = "-e -B0.5"
build_src_flags =
  -I firmware/variants/m328p
  ${common.us_build_flags}
build_src_filter =
  ${common.build_src_filter}
  +<../variants/m328p>

[env:openevse_latest]
platform = atmelavr
board = openevse
framework = arduino
lib_deps = ${common.lib_deps}
upload_protocol = ${m328p.upload_protocol}
upload_flags = ${m328p.upload_flags}
build_src_flags=
  ${common.us_build_flags}
  ${m328p.build_src_flags}
  -D 'VERSION="${common.version}"'

[env:openevse]
platform = atmelavr@3.4.0
board = openevse
framework = arduino
lib_deps = ${common.lib_deps}
upload_protocol = ${m328p.upload_protocol}
upload_flags = ${m328p.upload_flags}
build_src_filter =
  ${m328p.build_src_filter}
build_src_flags=
  ${m328p.build_src_flags}
  -D 'VERSION="${common.version}"'

# v6 CGMI OpenEVSE
[env:openevse_v6]
extends = env:openevse
build_src_flags=
  ${m328p.build_src_flags}
  -D ENABLE_CGMI
  -D NO_GROUND_RECORD_DELAY=2000
  -D NO_AUTOSVCLEVEL
  -D DEFAULT_SERVICE_LEVEL=2
  -D BOOTLOCK
  #-D BTN_MENU
  #-D RTC
  -D 'VERSION="${common.version}.CGMI"'

# EU OpenEVSE
[env:openevse_eu]
extends = env:openevse
build_src_flags=
  ${m328p.build_src_flags}
  ${common.eu_build_flags}
  -D MV_FOR_L2=230000L
  -D 'VERSION="${common.version}.EU"'

# Non-tethered T2 EmonEVSE single-phase
[env:emonevse]
extends = env:openevse
build_src_flags=
  ${m328p.build_src_flags}
  ${common.eu_build_flags}
  -D PP_AUTO_AMPACITY
  -D MV_FOR_L2=230000L
  -D 'VERSION="${common.version}.T2"'

# Non-tethered T2 EmonEVSE three-phase
# Deprecated, unneeded with wifi fw > 4.1.7
; [env:emonevse_3ph]
; extends = env:openevse
; build_src_flags=
;   ${common.eu_build_flags}
;   -D PP_AUTO_AMPACITY
;   -D THREEPHASE
;   -D 'VERSION="${common.version}.3P"'


